# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
#    - 'spec/**/*'
    - 'node_modules/**/*'
  DisplayCopNames: true

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'config/**/*'
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 30

Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/**/*'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

#ネストの上限
RSpec/NestedGroups:
  Enabled: false

#contextの書き方の制限
RSpec/ContextWording:
  Enabled: false

#exampleの書き方の制限
RSpec/ExampleWording:
  Enabled: false

#subjectに関連した名前をつける制限
RSpec/NamedSubject:
  Enabled: false

#1個のテスト(it)の行数制限
RSpec/ExampleLength:
  Max: 10

#let使用の推奨の制限
RSpec/InstanceVariable:
  Enabled: false
